openapi: 3.0.3
info:
  title: Pokemon Dashboard - Trainer Lookup API
  description: |
    Internal API for trainer lookup functionality.
    This documents the response schema including the new nickname field.
  version: 1.1.0

paths:
  /api/lookup:
    get:
      summary: Lookup trainer by name
      description: Retrieves trainer data and their selected Pokemon (if any)
      parameters:
        - name: name
          in: query
          required: true
          schema:
            type: string
          description: Trainer name to lookup
      responses:
        '200':
          description: Successful lookup
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LookupSuccessResponse'
        '400':
          description: Missing or invalid trainer name
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LookupErrorResponse'
        '404':
          description: Trainer not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LookupErrorResponse'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LookupErrorResponse'

components:
  schemas:
    LookupSuccessResponse:
      type: object
      required:
        - success
        - data
      properties:
        success:
          type: boolean
          enum: [true]
        data:
          $ref: '#/components/schemas/TrainerData'

    LookupErrorResponse:
      type: object
      required:
        - success
        - error
      properties:
        success:
          type: boolean
          enum: [false]
        error:
          type: object
          required:
            - type
            - message
          properties:
            type:
              type: string
              enum: [not_found, validation, network]
            message:
              type: string

    TrainerData:
      type: object
      required:
        - trainer_id
        - trainer_name
      properties:
        trainer_id:
          type: string
          format: uuid
          description: Unique trainer identifier
        trainer_name:
          type: string
          description: Display name of the trainer
        pokemon:
          $ref: '#/components/schemas/Pokemon'
          nullable: true
          description: Selected Pokemon (null if none selected)

    Pokemon:
      type: object
      required:
        - uuid
        - number
        - name
        - types
      properties:
        uuid:
          type: string
          format: uuid
          description: Unique Pokemon instance identifier
        number:
          type: integer
          minimum: 1
          maximum: 151
          description: Pokedex number
        name:
          type: string
          description: Pokemon species name (lowercase)
          example: pikachu
        types:
          type: array
          items:
            type: string
          minItems: 1
          maxItems: 2
          description: Pokemon type(s)
          example: [electric]
        nickname:
          type: string
          nullable: true
          maxLength: 12
          description: |
            Optional trainer-assigned nickname.
            - null or empty string = no nickname assigned
            - Non-empty string = display as primary name
          example: Sparky
